
version = "1.0";

application:
{
  window:
  {
    size = { w = 640; h = 480; };
  };

  rom:
  {
    path: "C:\code\emu\gb-test-roms-master\halt_bug.gb"
  }

  bios: 
  {
      path: "C:\code\emu\gb_bios.bin"
  }
};