// Generated from scripts/opcodes.json (https://gbdev.io/gb-opcodes/Opcodes.json).
//
// DO NOT EDIT THIS FILE BY HAND. Regenerate via scripts/gen_ops.py.
// Hand-written instruction bodies live in src/opcodes.cpp and are NOT
// touched by the generator.

// clang-format off

#pragma once
#ifndef _H_OPCODES_H_
#define _H_OPCODES_H_

#include <array>
#include <cstdint>

namespace gbemu {
	struct cpu;

	namespace ops {
		void nop(cpu&);
		void ld_bc_d16(cpu&);
		void ld__bc__a(cpu&);
		void inc_bc(cpu&);
		void inc_b(cpu&);
		void dec_b(cpu&);
		void ld_b_d8(cpu&);
		void rlca(cpu&);
		void ld__a16__sp(cpu&);
		void add_hl_bc(cpu&);
		void ld_a__bc_(cpu&);
		void dec_bc(cpu&);
		void inc_c(cpu&);
		void dec_c(cpu&);
		void ld_c_d8(cpu&);
		void rrca(cpu&);
		void stop(cpu&);
		void ld_de_d16(cpu&);
		void ld__de__a(cpu&);
		void inc_de(cpu&);
		void inc_d(cpu&);
		void dec_d(cpu&);
		void ld_d_d8(cpu&);
		void rla(cpu&);
		void jr_s8(cpu&);
		void add_hl_de(cpu&);
		void ld_a__de_(cpu&);
		void dec_de(cpu&);
		void inc_e(cpu&);
		void dec_e(cpu&);
		void ld_e_d8(cpu&);
		void rra(cpu&);
		void jr_nz_s8(cpu&);
		void ld_hl_d16(cpu&);
		void ld__hlp__a(cpu&);
		void inc_hl(cpu&);
		void inc_h(cpu&);
		void dec_h(cpu&);
		void ld_h_d8(cpu&);
		void daa(cpu&);
		void jr_z_s8(cpu&);
		void add_hl_hl(cpu&);
		void ld_a__hlp_(cpu&);
		void dec_hl(cpu&);
		void inc_l(cpu&);
		void dec_l(cpu&);
		void ld_l_d8(cpu&);
		void cpl(cpu&);
		void jr_nc_s8(cpu&);
		void ld_sp_d16(cpu&);
		void ld__hlm__a(cpu&);
		void inc_sp(cpu&);
		void inc__hl_(cpu&);
		void dec__hl_(cpu&);
		void ld__hl__d8(cpu&);
		void scf(cpu&);
		void jr_c_s8(cpu&);
		void add_hl_sp(cpu&);
		void ld_a__hlm_(cpu&);
		void dec_sp(cpu&);
		void inc_a(cpu&);
		void dec_a(cpu&);
		void ld_a_d8(cpu&);
		void ccf(cpu&);
		void ld_b_b(cpu&);
		void ld_b_c(cpu&);
		void ld_b_d(cpu&);
		void ld_b_e(cpu&);
		void ld_b_h(cpu&);
		void ld_b_l(cpu&);
		void ld_b__hl_(cpu&);
		void ld_b_a(cpu&);
		void ld_c_b(cpu&);
		void ld_c_c(cpu&);
		void ld_c_d(cpu&);
		void ld_c_e(cpu&);
		void ld_c_h(cpu&);
		void ld_c_l(cpu&);
		void ld_c__hl_(cpu&);
		void ld_c_a(cpu&);
		void ld_d_b(cpu&);
		void ld_d_c(cpu&);
		void ld_d_d(cpu&);
		void ld_d_e(cpu&);
		void ld_d_h(cpu&);
		void ld_d_l(cpu&);
		void ld_d__hl_(cpu&);
		void ld_d_a(cpu&);
		void ld_e_b(cpu&);
		void ld_e_c(cpu&);
		void ld_e_d(cpu&);
		void ld_e_e(cpu&);
		void ld_e_h(cpu&);
		void ld_e_l(cpu&);
		void ld_e__hl_(cpu&);
		void ld_e_a(cpu&);
		void ld_h_b(cpu&);
		void ld_h_c(cpu&);
		void ld_h_d(cpu&);
		void ld_h_e(cpu&);
		void ld_h_h(cpu&);
		void ld_h_l(cpu&);
		void ld_h__hl_(cpu&);
		void ld_h_a(cpu&);
		void ld_l_b(cpu&);
		void ld_l_c(cpu&);
		void ld_l_d(cpu&);
		void ld_l_e(cpu&);
		void ld_l_h(cpu&);
		void ld_l_l(cpu&);
		void ld_l__hl_(cpu&);
		void ld_l_a(cpu&);
		void ld__hl__b(cpu&);
		void ld__hl__c(cpu&);
		void ld__hl__d(cpu&);
		void ld__hl__e(cpu&);
		void ld__hl__h(cpu&);
		void ld__hl__l(cpu&);
		void halt(cpu&);
		void ld__hl__a(cpu&);
		void ld_a_b(cpu&);
		void ld_a_c(cpu&);
		void ld_a_d(cpu&);
		void ld_a_e(cpu&);
		void ld_a_h(cpu&);
		void ld_a_l(cpu&);
		void ld_a__hl_(cpu&);
		void ld_a_a(cpu&);
		void add_a_b(cpu&);
		void add_a_c(cpu&);
		void add_a_d(cpu&);
		void add_a_e(cpu&);
		void add_a_h(cpu&);
		void add_a_l(cpu&);
		void add_a__hl_(cpu&);
		void add_a_a(cpu&);
		void adc_a_b(cpu&);
		void adc_a_c(cpu&);
		void adc_a_d(cpu&);
		void adc_a_e(cpu&);
		void adc_a_h(cpu&);
		void adc_a_l(cpu&);
		void adc_a__hl_(cpu&);
		void adc_a_a(cpu&);
		void sub_b(cpu&);
		void sub_c(cpu&);
		void sub_d(cpu&);
		void sub_e(cpu&);
		void sub_h(cpu&);
		void sub_l(cpu&);
		void sub__hl_(cpu&);
		void sub_a(cpu&);
		void sbc_a_b(cpu&);
		void sbc_a_c(cpu&);
		void sbc_a_d(cpu&);
		void sbc_a_e(cpu&);
		void sbc_a_h(cpu&);
		void sbc_a_l(cpu&);
		void sbc_a__hl_(cpu&);
		void sbc_a_a(cpu&);
		void and_b(cpu&);
		void and_c(cpu&);
		void and_d(cpu&);
		void and_e(cpu&);
		void and_h(cpu&);
		void and_l(cpu&);
		void and__hl_(cpu&);
		void and_a(cpu&);
		void xor_b(cpu&);
		void xor_c(cpu&);
		void xor_d(cpu&);
		void xor_e(cpu&);
		void xor_h(cpu&);
		void xor_l(cpu&);
		void xor__hl_(cpu&);
		void xor_a(cpu&);
		void or_b(cpu&);
		void or_c(cpu&);
		void or_d(cpu&);
		void or_e(cpu&);
		void or_h(cpu&);
		void or_l(cpu&);
		void or__hl_(cpu&);
		void or_a(cpu&);
		void cp_b(cpu&);
		void cp_c(cpu&);
		void cp_d(cpu&);
		void cp_e(cpu&);
		void cp_h(cpu&);
		void cp_l(cpu&);
		void cp__hl_(cpu&);
		void cp_a(cpu&);
		void ret_nz(cpu&);
		void pop_bc(cpu&);
		void jp_nz_a16(cpu&);
		void jp_a16(cpu&);
		void call_nz_a16(cpu&);
		void push_bc(cpu&);
		void add_a_d8(cpu&);
		void rst_0(cpu&);
		void ret_z(cpu&);
		void ret(cpu&);
		void jp_z_a16(cpu&);
		void call_z_a16(cpu&);
		void call_a16(cpu&);
		void adc_a_d8(cpu&);
		void rst_1(cpu&);
		void ret_nc(cpu&);
		void pop_de(cpu&);
		void jp_nc_a16(cpu&);
		void call_nc_a16(cpu&);
		void push_de(cpu&);
		void sub_d8(cpu&);
		void rst_2(cpu&);
		void ret_c(cpu&);
		void reti(cpu&);
		void jp_c_a16(cpu&);
		void call_c_a16(cpu&);
		void sbc_a_d8(cpu&);
		void rst_3(cpu&);
		void ld__a8__a(cpu&);
		void pop_hl(cpu&);
		void ld__c__a(cpu&);
		void push_hl(cpu&);
		void and_d8(cpu&);
		void rst_4(cpu&);
		void add_sp_s8(cpu&);
		void jp_hl(cpu&);
		void ld__a16__a(cpu&);
		void xor_d8(cpu&);
		void rst_5(cpu&);
		void ld_a__a8_(cpu&);
		void pop_af(cpu&);
		void ld_a__c_(cpu&);
		void di(cpu&);
		void push_af(cpu&);
		void or_d8(cpu&);
		void rst_6(cpu&);
		void ld_hl_spps8(cpu&);
		void ld_sp_hl(cpu&);
		void ld_a__a16_(cpu&);
		void ei(cpu&);
		void cp_d8(cpu&);
		void rst_7(cpu&);
		void rlc_b(cpu&);
		void rlc_c(cpu&);
		void rlc_d(cpu&);
		void rlc_e(cpu&);
		void rlc_h(cpu&);
		void rlc_l(cpu&);
		void rlc__hl_(cpu&);
		void rlc_a(cpu&);
		void rrc_b(cpu&);
		void rrc_c(cpu&);
		void rrc_d(cpu&);
		void rrc_e(cpu&);
		void rrc_h(cpu&);
		void rrc_l(cpu&);
		void rrc__hl_(cpu&);
		void rrc_a(cpu&);
		void rl_b(cpu&);
		void rl_c(cpu&);
		void rl_d(cpu&);
		void rl_e(cpu&);
		void rl_h(cpu&);
		void rl_l(cpu&);
		void rl__hl_(cpu&);
		void rl_a(cpu&);
		void rr_b(cpu&);
		void rr_c(cpu&);
		void rr_d(cpu&);
		void rr_e(cpu&);
		void rr_h(cpu&);
		void rr_l(cpu&);
		void rr__hl_(cpu&);
		void rr_a(cpu&);
		void sla_b(cpu&);
		void sla_c(cpu&);
		void sla_d(cpu&);
		void sla_e(cpu&);
		void sla_h(cpu&);
		void sla_l(cpu&);
		void sla__hl_(cpu&);
		void sla_a(cpu&);
		void sra_b(cpu&);
		void sra_c(cpu&);
		void sra_d(cpu&);
		void sra_e(cpu&);
		void sra_h(cpu&);
		void sra_l(cpu&);
		void sra__hl_(cpu&);
		void sra_a(cpu&);
		void swap_b(cpu&);
		void swap_c(cpu&);
		void swap_d(cpu&);
		void swap_e(cpu&);
		void swap_h(cpu&);
		void swap_l(cpu&);
		void swap__hl_(cpu&);
		void swap_a(cpu&);
		void srl_b(cpu&);
		void srl_c(cpu&);
		void srl_d(cpu&);
		void srl_e(cpu&);
		void srl_h(cpu&);
		void srl_l(cpu&);
		void srl__hl_(cpu&);
		void srl_a(cpu&);
		void bit_0_b(cpu&);
		void bit_0_c(cpu&);
		void bit_0_d(cpu&);
		void bit_0_e(cpu&);
		void bit_0_h(cpu&);
		void bit_0_l(cpu&);
		void bit_0__hl_(cpu&);
		void bit_0_a(cpu&);
		void bit_1_b(cpu&);
		void bit_1_c(cpu&);
		void bit_1_d(cpu&);
		void bit_1_e(cpu&);
		void bit_1_h(cpu&);
		void bit_1_l(cpu&);
		void bit_1__hl_(cpu&);
		void bit_1_a(cpu&);
		void bit_2_b(cpu&);
		void bit_2_c(cpu&);
		void bit_2_d(cpu&);
		void bit_2_e(cpu&);
		void bit_2_h(cpu&);
		void bit_2_l(cpu&);
		void bit_2__hl_(cpu&);
		void bit_2_a(cpu&);
		void bit_3_b(cpu&);
		void bit_3_c(cpu&);
		void bit_3_d(cpu&);
		void bit_3_e(cpu&);
		void bit_3_h(cpu&);
		void bit_3_l(cpu&);
		void bit_3__hl_(cpu&);
		void bit_3_a(cpu&);
		void bit_4_b(cpu&);
		void bit_4_c(cpu&);
		void bit_4_d(cpu&);
		void bit_4_e(cpu&);
		void bit_4_h(cpu&);
		void bit_4_l(cpu&);
		void bit_4__hl_(cpu&);
		void bit_4_a(cpu&);
		void bit_5_b(cpu&);
		void bit_5_c(cpu&);
		void bit_5_d(cpu&);
		void bit_5_e(cpu&);
		void bit_5_h(cpu&);
		void bit_5_l(cpu&);
		void bit_5__hl_(cpu&);
		void bit_5_a(cpu&);
		void bit_6_b(cpu&);
		void bit_6_c(cpu&);
		void bit_6_d(cpu&);
		void bit_6_e(cpu&);
		void bit_6_h(cpu&);
		void bit_6_l(cpu&);
		void bit_6__hl_(cpu&);
		void bit_6_a(cpu&);
		void bit_7_b(cpu&);
		void bit_7_c(cpu&);
		void bit_7_d(cpu&);
		void bit_7_e(cpu&);
		void bit_7_h(cpu&);
		void bit_7_l(cpu&);
		void bit_7__hl_(cpu&);
		void bit_7_a(cpu&);
		void res_0_b(cpu&);
		void res_0_c(cpu&);
		void res_0_d(cpu&);
		void res_0_e(cpu&);
		void res_0_h(cpu&);
		void res_0_l(cpu&);
		void res_0__hl_(cpu&);
		void res_0_a(cpu&);
		void res_1_b(cpu&);
		void res_1_c(cpu&);
		void res_1_d(cpu&);
		void res_1_e(cpu&);
		void res_1_h(cpu&);
		void res_1_l(cpu&);
		void res_1__hl_(cpu&);
		void res_1_a(cpu&);
		void res_2_b(cpu&);
		void res_2_c(cpu&);
		void res_2_d(cpu&);
		void res_2_e(cpu&);
		void res_2_h(cpu&);
		void res_2_l(cpu&);
		void res_2__hl_(cpu&);
		void res_2_a(cpu&);
		void res_3_b(cpu&);
		void res_3_c(cpu&);
		void res_3_d(cpu&);
		void res_3_e(cpu&);
		void res_3_h(cpu&);
		void res_3_l(cpu&);
		void res_3__hl_(cpu&);
		void res_3_a(cpu&);
		void res_4_b(cpu&);
		void res_4_c(cpu&);
		void res_4_d(cpu&);
		void res_4_e(cpu&);
		void res_4_h(cpu&);
		void res_4_l(cpu&);
		void res_4__hl_(cpu&);
		void res_4_a(cpu&);
		void res_5_b(cpu&);
		void res_5_c(cpu&);
		void res_5_d(cpu&);
		void res_5_e(cpu&);
		void res_5_h(cpu&);
		void res_5_l(cpu&);
		void res_5__hl_(cpu&);
		void res_5_a(cpu&);
		void res_6_b(cpu&);
		void res_6_c(cpu&);
		void res_6_d(cpu&);
		void res_6_e(cpu&);
		void res_6_h(cpu&);
		void res_6_l(cpu&);
		void res_6__hl_(cpu&);
		void res_6_a(cpu&);
		void res_7_b(cpu&);
		void res_7_c(cpu&);
		void res_7_d(cpu&);
		void res_7_e(cpu&);
		void res_7_h(cpu&);
		void res_7_l(cpu&);
		void res_7__hl_(cpu&);
		void res_7_a(cpu&);
		void set_0_b(cpu&);
		void set_0_c(cpu&);
		void set_0_d(cpu&);
		void set_0_e(cpu&);
		void set_0_h(cpu&);
		void set_0_l(cpu&);
		void set_0__hl_(cpu&);
		void set_0_a(cpu&);
		void set_1_b(cpu&);
		void set_1_c(cpu&);
		void set_1_d(cpu&);
		void set_1_e(cpu&);
		void set_1_h(cpu&);
		void set_1_l(cpu&);
		void set_1__hl_(cpu&);
		void set_1_a(cpu&);
		void set_2_b(cpu&);
		void set_2_c(cpu&);
		void set_2_d(cpu&);
		void set_2_e(cpu&);
		void set_2_h(cpu&);
		void set_2_l(cpu&);
		void set_2__hl_(cpu&);
		void set_2_a(cpu&);
		void set_3_b(cpu&);
		void set_3_c(cpu&);
		void set_3_d(cpu&);
		void set_3_e(cpu&);
		void set_3_h(cpu&);
		void set_3_l(cpu&);
		void set_3__hl_(cpu&);
		void set_3_a(cpu&);
		void set_4_b(cpu&);
		void set_4_c(cpu&);
		void set_4_d(cpu&);
		void set_4_e(cpu&);
		void set_4_h(cpu&);
		void set_4_l(cpu&);
		void set_4__hl_(cpu&);
		void set_4_a(cpu&);
		void set_5_b(cpu&);
		void set_5_c(cpu&);
		void set_5_d(cpu&);
		void set_5_e(cpu&);
		void set_5_h(cpu&);
		void set_5_l(cpu&);
		void set_5__hl_(cpu&);
		void set_5_a(cpu&);
		void set_6_b(cpu&);
		void set_6_c(cpu&);
		void set_6_d(cpu&);
		void set_6_e(cpu&);
		void set_6_h(cpu&);
		void set_6_l(cpu&);
		void set_6__hl_(cpu&);
		void set_6_a(cpu&);
		void set_7_b(cpu&);
		void set_7_c(cpu&);
		void set_7_d(cpu&);
		void set_7_e(cpu&);
		void set_7_h(cpu&);
		void set_7_l(cpu&);
		void set_7__hl_(cpu&);
		void set_7_a(cpu&);
	} // namespace ops

	struct instr_entry {
		void (*fn)(cpu&);
		std::uint8_t cycles;
		std::uint8_t cycles_taken;
	};

	inline constexpr std::array<instr_entry, 256> dispatch_main = {{
		{ &ops::nop, 4, 4 },  // 0x00
		{ &ops::ld_bc_d16, 12, 12 },  // 0x01
		{ &ops::ld__bc__a, 8, 8 },  // 0x02
		{ &ops::inc_bc, 8, 8 },  // 0x03
		{ &ops::inc_b, 4, 4 },  // 0x04
		{ &ops::dec_b, 4, 4 },  // 0x05
		{ &ops::ld_b_d8, 8, 8 },  // 0x06
		{ &ops::rlca, 4, 4 },  // 0x07
		{ &ops::ld__a16__sp, 20, 20 },  // 0x08
		{ &ops::add_hl_bc, 8, 8 },  // 0x09
		{ &ops::ld_a__bc_, 8, 8 },  // 0x0A
		{ &ops::dec_bc, 8, 8 },  // 0x0B
		{ &ops::inc_c, 4, 4 },  // 0x0C
		{ &ops::dec_c, 4, 4 },  // 0x0D
		{ &ops::ld_c_d8, 8, 8 },  // 0x0E
		{ &ops::rrca, 4, 4 },  // 0x0F
		{ &ops::stop, 4, 4 },  // 0x10
		{ &ops::ld_de_d16, 12, 12 },  // 0x11
		{ &ops::ld__de__a, 8, 8 },  // 0x12
		{ &ops::inc_de, 8, 8 },  // 0x13
		{ &ops::inc_d, 4, 4 },  // 0x14
		{ &ops::dec_d, 4, 4 },  // 0x15
		{ &ops::ld_d_d8, 8, 8 },  // 0x16
		{ &ops::rla, 4, 4 },  // 0x17
		{ &ops::jr_s8, 12, 12 },  // 0x18
		{ &ops::add_hl_de, 8, 8 },  // 0x19
		{ &ops::ld_a__de_, 8, 8 },  // 0x1A
		{ &ops::dec_de, 8, 8 },  // 0x1B
		{ &ops::inc_e, 4, 4 },  // 0x1C
		{ &ops::dec_e, 4, 4 },  // 0x1D
		{ &ops::ld_e_d8, 8, 8 },  // 0x1E
		{ &ops::rra, 4, 4 },  // 0x1F
		{ &ops::jr_nz_s8, 8, 12 },  // 0x20
		{ &ops::ld_hl_d16, 12, 12 },  // 0x21
		{ &ops::ld__hlp__a, 8, 8 },  // 0x22
		{ &ops::inc_hl, 8, 8 },  // 0x23
		{ &ops::inc_h, 4, 4 },  // 0x24
		{ &ops::dec_h, 4, 4 },  // 0x25
		{ &ops::ld_h_d8, 8, 8 },  // 0x26
		{ &ops::daa, 4, 4 },  // 0x27
		{ &ops::jr_z_s8, 8, 12 },  // 0x28
		{ &ops::add_hl_hl, 8, 8 },  // 0x29
		{ &ops::ld_a__hlp_, 8, 8 },  // 0x2A
		{ &ops::dec_hl, 8, 8 },  // 0x2B
		{ &ops::inc_l, 4, 4 },  // 0x2C
		{ &ops::dec_l, 4, 4 },  // 0x2D
		{ &ops::ld_l_d8, 8, 8 },  // 0x2E
		{ &ops::cpl, 4, 4 },  // 0x2F
		{ &ops::jr_nc_s8, 8, 12 },  // 0x30
		{ &ops::ld_sp_d16, 12, 12 },  // 0x31
		{ &ops::ld__hlm__a, 8, 8 },  // 0x32
		{ &ops::inc_sp, 8, 8 },  // 0x33
		{ &ops::inc__hl_, 12, 12 },  // 0x34
		{ &ops::dec__hl_, 12, 12 },  // 0x35
		{ &ops::ld__hl__d8, 12, 12 },  // 0x36
		{ &ops::scf, 4, 4 },  // 0x37
		{ &ops::jr_c_s8, 8, 12 },  // 0x38
		{ &ops::add_hl_sp, 8, 8 },  // 0x39
		{ &ops::ld_a__hlm_, 8, 8 },  // 0x3A
		{ &ops::dec_sp, 8, 8 },  // 0x3B
		{ &ops::inc_a, 4, 4 },  // 0x3C
		{ &ops::dec_a, 4, 4 },  // 0x3D
		{ &ops::ld_a_d8, 8, 8 },  // 0x3E
		{ &ops::ccf, 4, 4 },  // 0x3F
		{ &ops::ld_b_b, 4, 4 },  // 0x40
		{ &ops::ld_b_c, 4, 4 },  // 0x41
		{ &ops::ld_b_d, 4, 4 },  // 0x42
		{ &ops::ld_b_e, 4, 4 },  // 0x43
		{ &ops::ld_b_h, 4, 4 },  // 0x44
		{ &ops::ld_b_l, 4, 4 },  // 0x45
		{ &ops::ld_b__hl_, 8, 8 },  // 0x46
		{ &ops::ld_b_a, 4, 4 },  // 0x47
		{ &ops::ld_c_b, 4, 4 },  // 0x48
		{ &ops::ld_c_c, 4, 4 },  // 0x49
		{ &ops::ld_c_d, 4, 4 },  // 0x4A
		{ &ops::ld_c_e, 4, 4 },  // 0x4B
		{ &ops::ld_c_h, 4, 4 },  // 0x4C
		{ &ops::ld_c_l, 4, 4 },  // 0x4D
		{ &ops::ld_c__hl_, 8, 8 },  // 0x4E
		{ &ops::ld_c_a, 4, 4 },  // 0x4F
		{ &ops::ld_d_b, 4, 4 },  // 0x50
		{ &ops::ld_d_c, 4, 4 },  // 0x51
		{ &ops::ld_d_d, 4, 4 },  // 0x52
		{ &ops::ld_d_e, 4, 4 },  // 0x53
		{ &ops::ld_d_h, 4, 4 },  // 0x54
		{ &ops::ld_d_l, 4, 4 },  // 0x55
		{ &ops::ld_d__hl_, 8, 8 },  // 0x56
		{ &ops::ld_d_a, 4, 4 },  // 0x57
		{ &ops::ld_e_b, 4, 4 },  // 0x58
		{ &ops::ld_e_c, 4, 4 },  // 0x59
		{ &ops::ld_e_d, 4, 4 },  // 0x5A
		{ &ops::ld_e_e, 4, 4 },  // 0x5B
		{ &ops::ld_e_h, 4, 4 },  // 0x5C
		{ &ops::ld_e_l, 4, 4 },  // 0x5D
		{ &ops::ld_e__hl_, 8, 8 },  // 0x5E
		{ &ops::ld_e_a, 4, 4 },  // 0x5F
		{ &ops::ld_h_b, 4, 4 },  // 0x60
		{ &ops::ld_h_c, 4, 4 },  // 0x61
		{ &ops::ld_h_d, 4, 4 },  // 0x62
		{ &ops::ld_h_e, 4, 4 },  // 0x63
		{ &ops::ld_h_h, 4, 4 },  // 0x64
		{ &ops::ld_h_l, 4, 4 },  // 0x65
		{ &ops::ld_h__hl_, 8, 8 },  // 0x66
		{ &ops::ld_h_a, 4, 4 },  // 0x67
		{ &ops::ld_l_b, 4, 4 },  // 0x68
		{ &ops::ld_l_c, 4, 4 },  // 0x69
		{ &ops::ld_l_d, 4, 4 },  // 0x6A
		{ &ops::ld_l_e, 4, 4 },  // 0x6B
		{ &ops::ld_l_h, 4, 4 },  // 0x6C
		{ &ops::ld_l_l, 4, 4 },  // 0x6D
		{ &ops::ld_l__hl_, 8, 8 },  // 0x6E
		{ &ops::ld_l_a, 4, 4 },  // 0x6F
		{ &ops::ld__hl__b, 8, 8 },  // 0x70
		{ &ops::ld__hl__c, 8, 8 },  // 0x71
		{ &ops::ld__hl__d, 8, 8 },  // 0x72
		{ &ops::ld__hl__e, 8, 8 },  // 0x73
		{ &ops::ld__hl__h, 8, 8 },  // 0x74
		{ &ops::ld__hl__l, 8, 8 },  // 0x75
		{ &ops::halt, 4, 4 },  // 0x76
		{ &ops::ld__hl__a, 8, 8 },  // 0x77
		{ &ops::ld_a_b, 4, 4 },  // 0x78
		{ &ops::ld_a_c, 4, 4 },  // 0x79
		{ &ops::ld_a_d, 4, 4 },  // 0x7A
		{ &ops::ld_a_e, 4, 4 },  // 0x7B
		{ &ops::ld_a_h, 4, 4 },  // 0x7C
		{ &ops::ld_a_l, 4, 4 },  // 0x7D
		{ &ops::ld_a__hl_, 8, 8 },  // 0x7E
		{ &ops::ld_a_a, 4, 4 },  // 0x7F
		{ &ops::add_a_b, 4, 4 },  // 0x80
		{ &ops::add_a_c, 4, 4 },  // 0x81
		{ &ops::add_a_d, 4, 4 },  // 0x82
		{ &ops::add_a_e, 4, 4 },  // 0x83
		{ &ops::add_a_h, 4, 4 },  // 0x84
		{ &ops::add_a_l, 4, 4 },  // 0x85
		{ &ops::add_a__hl_, 8, 8 },  // 0x86
		{ &ops::add_a_a, 4, 4 },  // 0x87
		{ &ops::adc_a_b, 4, 4 },  // 0x88
		{ &ops::adc_a_c, 4, 4 },  // 0x89
		{ &ops::adc_a_d, 4, 4 },  // 0x8A
		{ &ops::adc_a_e, 4, 4 },  // 0x8B
		{ &ops::adc_a_h, 4, 4 },  // 0x8C
		{ &ops::adc_a_l, 4, 4 },  // 0x8D
		{ &ops::adc_a__hl_, 8, 8 },  // 0x8E
		{ &ops::adc_a_a, 4, 4 },  // 0x8F
		{ &ops::sub_b, 4, 4 },  // 0x90
		{ &ops::sub_c, 4, 4 },  // 0x91
		{ &ops::sub_d, 4, 4 },  // 0x92
		{ &ops::sub_e, 4, 4 },  // 0x93
		{ &ops::sub_h, 4, 4 },  // 0x94
		{ &ops::sub_l, 4, 4 },  // 0x95
		{ &ops::sub__hl_, 8, 8 },  // 0x96
		{ &ops::sub_a, 4, 4 },  // 0x97
		{ &ops::sbc_a_b, 4, 4 },  // 0x98
		{ &ops::sbc_a_c, 4, 4 },  // 0x99
		{ &ops::sbc_a_d, 4, 4 },  // 0x9A
		{ &ops::sbc_a_e, 4, 4 },  // 0x9B
		{ &ops::sbc_a_h, 4, 4 },  // 0x9C
		{ &ops::sbc_a_l, 4, 4 },  // 0x9D
		{ &ops::sbc_a__hl_, 8, 8 },  // 0x9E
		{ &ops::sbc_a_a, 4, 4 },  // 0x9F
		{ &ops::and_b, 4, 4 },  // 0xA0
		{ &ops::and_c, 4, 4 },  // 0xA1
		{ &ops::and_d, 4, 4 },  // 0xA2
		{ &ops::and_e, 4, 4 },  // 0xA3
		{ &ops::and_h, 4, 4 },  // 0xA4
		{ &ops::and_l, 4, 4 },  // 0xA5
		{ &ops::and__hl_, 8, 8 },  // 0xA6
		{ &ops::and_a, 4, 4 },  // 0xA7
		{ &ops::xor_b, 4, 4 },  // 0xA8
		{ &ops::xor_c, 4, 4 },  // 0xA9
		{ &ops::xor_d, 4, 4 },  // 0xAA
		{ &ops::xor_e, 4, 4 },  // 0xAB
		{ &ops::xor_h, 4, 4 },  // 0xAC
		{ &ops::xor_l, 4, 4 },  // 0xAD
		{ &ops::xor__hl_, 8, 8 },  // 0xAE
		{ &ops::xor_a, 4, 4 },  // 0xAF
		{ &ops::or_b, 4, 4 },  // 0xB0
		{ &ops::or_c, 4, 4 },  // 0xB1
		{ &ops::or_d, 4, 4 },  // 0xB2
		{ &ops::or_e, 4, 4 },  // 0xB3
		{ &ops::or_h, 4, 4 },  // 0xB4
		{ &ops::or_l, 4, 4 },  // 0xB5
		{ &ops::or__hl_, 8, 8 },  // 0xB6
		{ &ops::or_a, 4, 4 },  // 0xB7
		{ &ops::cp_b, 4, 4 },  // 0xB8
		{ &ops::cp_c, 4, 4 },  // 0xB9
		{ &ops::cp_d, 4, 4 },  // 0xBA
		{ &ops::cp_e, 4, 4 },  // 0xBB
		{ &ops::cp_h, 4, 4 },  // 0xBC
		{ &ops::cp_l, 4, 4 },  // 0xBD
		{ &ops::cp__hl_, 8, 8 },  // 0xBE
		{ &ops::cp_a, 4, 4 },  // 0xBF
		{ &ops::ret_nz, 8, 20 },  // 0xC0
		{ &ops::pop_bc, 12, 12 },  // 0xC1
		{ &ops::jp_nz_a16, 12, 16 },  // 0xC2
		{ &ops::jp_a16, 16, 16 },  // 0xC3
		{ &ops::call_nz_a16, 12, 24 },  // 0xC4
		{ &ops::push_bc, 16, 16 },  // 0xC5
		{ &ops::add_a_d8, 8, 8 },  // 0xC6
		{ &ops::rst_0, 16, 16 },  // 0xC7
		{ &ops::ret_z, 8, 20 },  // 0xC8
		{ &ops::ret, 16, 16 },  // 0xC9
		{ &ops::jp_z_a16, 12, 16 },  // 0xCA
		{ nullptr, 0, 0 },  // 0xCB
		{ &ops::call_z_a16, 12, 24 },  // 0xCC
		{ &ops::call_a16, 24, 24 },  // 0xCD
		{ &ops::adc_a_d8, 8, 8 },  // 0xCE
		{ &ops::rst_1, 16, 16 },  // 0xCF
		{ &ops::ret_nc, 8, 20 },  // 0xD0
		{ &ops::pop_de, 12, 12 },  // 0xD1
		{ &ops::jp_nc_a16, 12, 16 },  // 0xD2
		{ nullptr, 0, 0 },  // 0xD3
		{ &ops::call_nc_a16, 12, 24 },  // 0xD4
		{ &ops::push_de, 16, 16 },  // 0xD5
		{ &ops::sub_d8, 8, 8 },  // 0xD6
		{ &ops::rst_2, 16, 16 },  // 0xD7
		{ &ops::ret_c, 8, 20 },  // 0xD8
		{ &ops::reti, 16, 16 },  // 0xD9
		{ &ops::jp_c_a16, 12, 16 },  // 0xDA
		{ nullptr, 0, 0 },  // 0xDB
		{ &ops::call_c_a16, 12, 24 },  // 0xDC
		{ nullptr, 0, 0 },  // 0xDD
		{ &ops::sbc_a_d8, 8, 8 },  // 0xDE
		{ &ops::rst_3, 16, 16 },  // 0xDF
		{ &ops::ld__a8__a, 12, 12 },  // 0xE0
		{ &ops::pop_hl, 12, 12 },  // 0xE1
		{ &ops::ld__c__a, 8, 8 },  // 0xE2
		{ nullptr, 0, 0 },  // 0xE3
		{ nullptr, 0, 0 },  // 0xE4
		{ &ops::push_hl, 16, 16 },  // 0xE5
		{ &ops::and_d8, 8, 8 },  // 0xE6
		{ &ops::rst_4, 16, 16 },  // 0xE7
		{ &ops::add_sp_s8, 16, 16 },  // 0xE8
		{ &ops::jp_hl, 4, 4 },  // 0xE9
		{ &ops::ld__a16__a, 16, 16 },  // 0xEA
		{ nullptr, 0, 0 },  // 0xEB
		{ nullptr, 0, 0 },  // 0xEC
		{ nullptr, 0, 0 },  // 0xED
		{ &ops::xor_d8, 8, 8 },  // 0xEE
		{ &ops::rst_5, 16, 16 },  // 0xEF
		{ &ops::ld_a__a8_, 12, 12 },  // 0xF0
		{ &ops::pop_af, 12, 12 },  // 0xF1
		{ &ops::ld_a__c_, 8, 8 },  // 0xF2
		{ &ops::di, 4, 4 },  // 0xF3
		{ nullptr, 0, 0 },  // 0xF4
		{ &ops::push_af, 16, 16 },  // 0xF5
		{ &ops::or_d8, 8, 8 },  // 0xF6
		{ &ops::rst_6, 16, 16 },  // 0xF7
		{ &ops::ld_hl_spps8, 12, 12 },  // 0xF8
		{ &ops::ld_sp_hl, 8, 8 },  // 0xF9
		{ &ops::ld_a__a16_, 16, 16 },  // 0xFA
		{ &ops::ei, 4, 4 },  // 0xFB
		{ nullptr, 0, 0 },  // 0xFC
		{ nullptr, 0, 0 },  // 0xFD
		{ &ops::cp_d8, 8, 8 },  // 0xFE
		{ &ops::rst_7, 16, 16 },  // 0xFF
	}};

	inline constexpr std::array<instr_entry, 256> dispatch_cb = {{
		{ &ops::rlc_b, 8, 8 },  // 0x00
		{ &ops::rlc_c, 8, 8 },  // 0x01
		{ &ops::rlc_d, 8, 8 },  // 0x02
		{ &ops::rlc_e, 8, 8 },  // 0x03
		{ &ops::rlc_h, 8, 8 },  // 0x04
		{ &ops::rlc_l, 8, 8 },  // 0x05
		{ &ops::rlc__hl_, 16, 16 },  // 0x06
		{ &ops::rlc_a, 8, 8 },  // 0x07
		{ &ops::rrc_b, 8, 8 },  // 0x08
		{ &ops::rrc_c, 8, 8 },  // 0x09
		{ &ops::rrc_d, 8, 8 },  // 0x0A
		{ &ops::rrc_e, 8, 8 },  // 0x0B
		{ &ops::rrc_h, 8, 8 },  // 0x0C
		{ &ops::rrc_l, 8, 8 },  // 0x0D
		{ &ops::rrc__hl_, 16, 16 },  // 0x0E
		{ &ops::rrc_a, 8, 8 },  // 0x0F
		{ &ops::rl_b, 8, 8 },  // 0x10
		{ &ops::rl_c, 8, 8 },  // 0x11
		{ &ops::rl_d, 8, 8 },  // 0x12
		{ &ops::rl_e, 8, 8 },  // 0x13
		{ &ops::rl_h, 8, 8 },  // 0x14
		{ &ops::rl_l, 8, 8 },  // 0x15
		{ &ops::rl__hl_, 16, 16 },  // 0x16
		{ &ops::rl_a, 8, 8 },  // 0x17
		{ &ops::rr_b, 8, 8 },  // 0x18
		{ &ops::rr_c, 8, 8 },  // 0x19
		{ &ops::rr_d, 8, 8 },  // 0x1A
		{ &ops::rr_e, 8, 8 },  // 0x1B
		{ &ops::rr_h, 8, 8 },  // 0x1C
		{ &ops::rr_l, 8, 8 },  // 0x1D
		{ &ops::rr__hl_, 16, 16 },  // 0x1E
		{ &ops::rr_a, 8, 8 },  // 0x1F
		{ &ops::sla_b, 8, 8 },  // 0x20
		{ &ops::sla_c, 8, 8 },  // 0x21
		{ &ops::sla_d, 8, 8 },  // 0x22
		{ &ops::sla_e, 8, 8 },  // 0x23
		{ &ops::sla_h, 8, 8 },  // 0x24
		{ &ops::sla_l, 8, 8 },  // 0x25
		{ &ops::sla__hl_, 16, 16 },  // 0x26
		{ &ops::sla_a, 8, 8 },  // 0x27
		{ &ops::sra_b, 8, 8 },  // 0x28
		{ &ops::sra_c, 8, 8 },  // 0x29
		{ &ops::sra_d, 8, 8 },  // 0x2A
		{ &ops::sra_e, 8, 8 },  // 0x2B
		{ &ops::sra_h, 8, 8 },  // 0x2C
		{ &ops::sra_l, 8, 8 },  // 0x2D
		{ &ops::sra__hl_, 16, 16 },  // 0x2E
		{ &ops::sra_a, 8, 8 },  // 0x2F
		{ &ops::swap_b, 8, 8 },  // 0x30
		{ &ops::swap_c, 8, 8 },  // 0x31
		{ &ops::swap_d, 8, 8 },  // 0x32
		{ &ops::swap_e, 8, 8 },  // 0x33
		{ &ops::swap_h, 8, 8 },  // 0x34
		{ &ops::swap_l, 8, 8 },  // 0x35
		{ &ops::swap__hl_, 16, 16 },  // 0x36
		{ &ops::swap_a, 8, 8 },  // 0x37
		{ &ops::srl_b, 8, 8 },  // 0x38
		{ &ops::srl_c, 8, 8 },  // 0x39
		{ &ops::srl_d, 8, 8 },  // 0x3A
		{ &ops::srl_e, 8, 8 },  // 0x3B
		{ &ops::srl_h, 8, 8 },  // 0x3C
		{ &ops::srl_l, 8, 8 },  // 0x3D
		{ &ops::srl__hl_, 16, 16 },  // 0x3E
		{ &ops::srl_a, 8, 8 },  // 0x3F
		{ &ops::bit_0_b, 8, 8 },  // 0x40
		{ &ops::bit_0_c, 8, 8 },  // 0x41
		{ &ops::bit_0_d, 8, 8 },  // 0x42
		{ &ops::bit_0_e, 8, 8 },  // 0x43
		{ &ops::bit_0_h, 8, 8 },  // 0x44
		{ &ops::bit_0_l, 8, 8 },  // 0x45
		{ &ops::bit_0__hl_, 12, 12 },  // 0x46
		{ &ops::bit_0_a, 8, 8 },  // 0x47
		{ &ops::bit_1_b, 8, 8 },  // 0x48
		{ &ops::bit_1_c, 8, 8 },  // 0x49
		{ &ops::bit_1_d, 8, 8 },  // 0x4A
		{ &ops::bit_1_e, 8, 8 },  // 0x4B
		{ &ops::bit_1_h, 8, 8 },  // 0x4C
		{ &ops::bit_1_l, 8, 8 },  // 0x4D
		{ &ops::bit_1__hl_, 12, 12 },  // 0x4E
		{ &ops::bit_1_a, 8, 8 },  // 0x4F
		{ &ops::bit_2_b, 8, 8 },  // 0x50
		{ &ops::bit_2_c, 8, 8 },  // 0x51
		{ &ops::bit_2_d, 8, 8 },  // 0x52
		{ &ops::bit_2_e, 8, 8 },  // 0x53
		{ &ops::bit_2_h, 8, 8 },  // 0x54
		{ &ops::bit_2_l, 8, 8 },  // 0x55
		{ &ops::bit_2__hl_, 12, 12 },  // 0x56
		{ &ops::bit_2_a, 8, 8 },  // 0x57
		{ &ops::bit_3_b, 8, 8 },  // 0x58
		{ &ops::bit_3_c, 8, 8 },  // 0x59
		{ &ops::bit_3_d, 8, 8 },  // 0x5A
		{ &ops::bit_3_e, 8, 8 },  // 0x5B
		{ &ops::bit_3_h, 8, 8 },  // 0x5C
		{ &ops::bit_3_l, 8, 8 },  // 0x5D
		{ &ops::bit_3__hl_, 12, 12 },  // 0x5E
		{ &ops::bit_3_a, 8, 8 },  // 0x5F
		{ &ops::bit_4_b, 8, 8 },  // 0x60
		{ &ops::bit_4_c, 8, 8 },  // 0x61
		{ &ops::bit_4_d, 8, 8 },  // 0x62
		{ &ops::bit_4_e, 8, 8 },  // 0x63
		{ &ops::bit_4_h, 8, 8 },  // 0x64
		{ &ops::bit_4_l, 8, 8 },  // 0x65
		{ &ops::bit_4__hl_, 12, 12 },  // 0x66
		{ &ops::bit_4_a, 8, 8 },  // 0x67
		{ &ops::bit_5_b, 8, 8 },  // 0x68
		{ &ops::bit_5_c, 8, 8 },  // 0x69
		{ &ops::bit_5_d, 8, 8 },  // 0x6A
		{ &ops::bit_5_e, 8, 8 },  // 0x6B
		{ &ops::bit_5_h, 8, 8 },  // 0x6C
		{ &ops::bit_5_l, 8, 8 },  // 0x6D
		{ &ops::bit_5__hl_, 12, 12 },  // 0x6E
		{ &ops::bit_5_a, 8, 8 },  // 0x6F
		{ &ops::bit_6_b, 8, 8 },  // 0x70
		{ &ops::bit_6_c, 8, 8 },  // 0x71
		{ &ops::bit_6_d, 8, 8 },  // 0x72
		{ &ops::bit_6_e, 8, 8 },  // 0x73
		{ &ops::bit_6_h, 8, 8 },  // 0x74
		{ &ops::bit_6_l, 8, 8 },  // 0x75
		{ &ops::bit_6__hl_, 12, 12 },  // 0x76
		{ &ops::bit_6_a, 8, 8 },  // 0x77
		{ &ops::bit_7_b, 8, 8 },  // 0x78
		{ &ops::bit_7_c, 8, 8 },  // 0x79
		{ &ops::bit_7_d, 8, 8 },  // 0x7A
		{ &ops::bit_7_e, 8, 8 },  // 0x7B
		{ &ops::bit_7_h, 8, 8 },  // 0x7C
		{ &ops::bit_7_l, 8, 8 },  // 0x7D
		{ &ops::bit_7__hl_, 12, 12 },  // 0x7E
		{ &ops::bit_7_a, 8, 8 },  // 0x7F
		{ &ops::res_0_b, 8, 8 },  // 0x80
		{ &ops::res_0_c, 8, 8 },  // 0x81
		{ &ops::res_0_d, 8, 8 },  // 0x82
		{ &ops::res_0_e, 8, 8 },  // 0x83
		{ &ops::res_0_h, 8, 8 },  // 0x84
		{ &ops::res_0_l, 8, 8 },  // 0x85
		{ &ops::res_0__hl_, 16, 16 },  // 0x86
		{ &ops::res_0_a, 8, 8 },  // 0x87
		{ &ops::res_1_b, 8, 8 },  // 0x88
		{ &ops::res_1_c, 8, 8 },  // 0x89
		{ &ops::res_1_d, 8, 8 },  // 0x8A
		{ &ops::res_1_e, 8, 8 },  // 0x8B
		{ &ops::res_1_h, 8, 8 },  // 0x8C
		{ &ops::res_1_l, 8, 8 },  // 0x8D
		{ &ops::res_1__hl_, 16, 16 },  // 0x8E
		{ &ops::res_1_a, 8, 8 },  // 0x8F
		{ &ops::res_2_b, 8, 8 },  // 0x90
		{ &ops::res_2_c, 8, 8 },  // 0x91
		{ &ops::res_2_d, 8, 8 },  // 0x92
		{ &ops::res_2_e, 8, 8 },  // 0x93
		{ &ops::res_2_h, 8, 8 },  // 0x94
		{ &ops::res_2_l, 8, 8 },  // 0x95
		{ &ops::res_2__hl_, 16, 16 },  // 0x96
		{ &ops::res_2_a, 8, 8 },  // 0x97
		{ &ops::res_3_b, 8, 8 },  // 0x98
		{ &ops::res_3_c, 8, 8 },  // 0x99
		{ &ops::res_3_d, 8, 8 },  // 0x9A
		{ &ops::res_3_e, 8, 8 },  // 0x9B
		{ &ops::res_3_h, 8, 8 },  // 0x9C
		{ &ops::res_3_l, 8, 8 },  // 0x9D
		{ &ops::res_3__hl_, 16, 16 },  // 0x9E
		{ &ops::res_3_a, 8, 8 },  // 0x9F
		{ &ops::res_4_b, 8, 8 },  // 0xA0
		{ &ops::res_4_c, 8, 8 },  // 0xA1
		{ &ops::res_4_d, 8, 8 },  // 0xA2
		{ &ops::res_4_e, 8, 8 },  // 0xA3
		{ &ops::res_4_h, 8, 8 },  // 0xA4
		{ &ops::res_4_l, 8, 8 },  // 0xA5
		{ &ops::res_4__hl_, 16, 16 },  // 0xA6
		{ &ops::res_4_a, 8, 8 },  // 0xA7
		{ &ops::res_5_b, 8, 8 },  // 0xA8
		{ &ops::res_5_c, 8, 8 },  // 0xA9
		{ &ops::res_5_d, 8, 8 },  // 0xAA
		{ &ops::res_5_e, 8, 8 },  // 0xAB
		{ &ops::res_5_h, 8, 8 },  // 0xAC
		{ &ops::res_5_l, 8, 8 },  // 0xAD
		{ &ops::res_5__hl_, 16, 16 },  // 0xAE
		{ &ops::res_5_a, 8, 8 },  // 0xAF
		{ &ops::res_6_b, 8, 8 },  // 0xB0
		{ &ops::res_6_c, 8, 8 },  // 0xB1
		{ &ops::res_6_d, 8, 8 },  // 0xB2
		{ &ops::res_6_e, 8, 8 },  // 0xB3
		{ &ops::res_6_h, 8, 8 },  // 0xB4
		{ &ops::res_6_l, 8, 8 },  // 0xB5
		{ &ops::res_6__hl_, 16, 16 },  // 0xB6
		{ &ops::res_6_a, 8, 8 },  // 0xB7
		{ &ops::res_7_b, 8, 8 },  // 0xB8
		{ &ops::res_7_c, 8, 8 },  // 0xB9
		{ &ops::res_7_d, 8, 8 },  // 0xBA
		{ &ops::res_7_e, 8, 8 },  // 0xBB
		{ &ops::res_7_h, 8, 8 },  // 0xBC
		{ &ops::res_7_l, 8, 8 },  // 0xBD
		{ &ops::res_7__hl_, 16, 16 },  // 0xBE
		{ &ops::res_7_a, 8, 8 },  // 0xBF
		{ &ops::set_0_b, 8, 8 },  // 0xC0
		{ &ops::set_0_c, 8, 8 },  // 0xC1
		{ &ops::set_0_d, 8, 8 },  // 0xC2
		{ &ops::set_0_e, 8, 8 },  // 0xC3
		{ &ops::set_0_h, 8, 8 },  // 0xC4
		{ &ops::set_0_l, 8, 8 },  // 0xC5
		{ &ops::set_0__hl_, 16, 16 },  // 0xC6
		{ &ops::set_0_a, 8, 8 },  // 0xC7
		{ &ops::set_1_b, 8, 8 },  // 0xC8
		{ &ops::set_1_c, 8, 8 },  // 0xC9
		{ &ops::set_1_d, 8, 8 },  // 0xCA
		{ &ops::set_1_e, 8, 8 },  // 0xCB
		{ &ops::set_1_h, 8, 8 },  // 0xCC
		{ &ops::set_1_l, 8, 8 },  // 0xCD
		{ &ops::set_1__hl_, 16, 16 },  // 0xCE
		{ &ops::set_1_a, 8, 8 },  // 0xCF
		{ &ops::set_2_b, 8, 8 },  // 0xD0
		{ &ops::set_2_c, 8, 8 },  // 0xD1
		{ &ops::set_2_d, 8, 8 },  // 0xD2
		{ &ops::set_2_e, 8, 8 },  // 0xD3
		{ &ops::set_2_h, 8, 8 },  // 0xD4
		{ &ops::set_2_l, 8, 8 },  // 0xD5
		{ &ops::set_2__hl_, 16, 16 },  // 0xD6
		{ &ops::set_2_a, 8, 8 },  // 0xD7
		{ &ops::set_3_b, 8, 8 },  // 0xD8
		{ &ops::set_3_c, 8, 8 },  // 0xD9
		{ &ops::set_3_d, 8, 8 },  // 0xDA
		{ &ops::set_3_e, 8, 8 },  // 0xDB
		{ &ops::set_3_h, 8, 8 },  // 0xDC
		{ &ops::set_3_l, 8, 8 },  // 0xDD
		{ &ops::set_3__hl_, 16, 16 },  // 0xDE
		{ &ops::set_3_a, 8, 8 },  // 0xDF
		{ &ops::set_4_b, 8, 8 },  // 0xE0
		{ &ops::set_4_c, 8, 8 },  // 0xE1
		{ &ops::set_4_d, 8, 8 },  // 0xE2
		{ &ops::set_4_e, 8, 8 },  // 0xE3
		{ &ops::set_4_h, 8, 8 },  // 0xE4
		{ &ops::set_4_l, 8, 8 },  // 0xE5
		{ &ops::set_4__hl_, 16, 16 },  // 0xE6
		{ &ops::set_4_a, 8, 8 },  // 0xE7
		{ &ops::set_5_b, 8, 8 },  // 0xE8
		{ &ops::set_5_c, 8, 8 },  // 0xE9
		{ &ops::set_5_d, 8, 8 },  // 0xEA
		{ &ops::set_5_e, 8, 8 },  // 0xEB
		{ &ops::set_5_h, 8, 8 },  // 0xEC
		{ &ops::set_5_l, 8, 8 },  // 0xED
		{ &ops::set_5__hl_, 16, 16 },  // 0xEE
		{ &ops::set_5_a, 8, 8 },  // 0xEF
		{ &ops::set_6_b, 8, 8 },  // 0xF0
		{ &ops::set_6_c, 8, 8 },  // 0xF1
		{ &ops::set_6_d, 8, 8 },  // 0xF2
		{ &ops::set_6_e, 8, 8 },  // 0xF3
		{ &ops::set_6_h, 8, 8 },  // 0xF4
		{ &ops::set_6_l, 8, 8 },  // 0xF5
		{ &ops::set_6__hl_, 16, 16 },  // 0xF6
		{ &ops::set_6_a, 8, 8 },  // 0xF7
		{ &ops::set_7_b, 8, 8 },  // 0xF8
		{ &ops::set_7_c, 8, 8 },  // 0xF9
		{ &ops::set_7_d, 8, 8 },  // 0xFA
		{ &ops::set_7_e, 8, 8 },  // 0xFB
		{ &ops::set_7_h, 8, 8 },  // 0xFC
		{ &ops::set_7_l, 8, 8 },  // 0xFD
		{ &ops::set_7__hl_, 16, 16 },  // 0xFE
		{ &ops::set_7_a, 8, 8 },  // 0xFF
	}};
} // namespace gbemu

#endif /* _H_OPCODES_H_ */
