"""Generate inc/opcodes.hpp from scripts/ops_db.json.

Emits ONLY the header. The implementation file src/opcodes.cpp contains
hand-written instruction bodies and is never touched by this generator.

The emitted DEF_INSTR macro now carries T-cycle metadata (cycles_not_taken,
cycles_taken). M-cycles from the JSON are converted to T-cycles (x4).
Conditional opcodes (JR cc / JP cc / CALL cc / RET cc) encode their cycle
count as "taken/not_taken" in M-cycles; everything else is a single value.

Usage:
    python gen_ops.py                         # writes ./opcodes.hpp from ./ops_db.json
    python gen_ops.py --out ../inc/opcodes.hpp
    python gen_ops.py --db ops_db.json --out -   # '-' prints to stdout
"""

import argparse
import json
import sys
from pathlib import Path


def make_cn(text: str) -> str:
    """Convert a mnemonic into a valid C++ identifier."""
    return (text
            .replace(' ', '_')
            .replace(',', '')
            .replace('(', '_').replace(')', '_')
            .replace('[', '_').replace(']', '_')
            .replace('+', 'P').replace('-', 'M')
            .lower())


def parse_cycles(raw: str) -> tuple[int, int]:
    """Parse the JSON 'cycles' field. Returns (cycles_not_taken, cycles_taken)
    in T-cycles. JSON values are M-cycles; multiply by 4.

    Examples:
        "1"   -> (4, 4)
        "3"   -> (12, 12)
        "3/2" -> (8, 12)   # JSON is "taken/not_taken"; we return (nt, t)
    """
    s = str(raw).strip()
    if '/' in s:
        taken_m, not_taken_m = s.split('/', 1)
        return (int(not_taken_m) * 4, int(taken_m) * 4)
    v = int(s) * 4
    return (v, v)


def format_opcode(raw: str) -> str:
    """Normalise an opCode string to '0xNNNN'. 2-char codes get a 0x00 prefix
    (non-CB), 4-char codes (CB-prefixed) are passed through."""
    return '0x00' + raw if len(raw) == 2 else '0x' + raw


HEADER_PREAMBLE = """// Generated from ops_db.json
// https://gist.github.com/bberak/ca001281bb8431d2706afd31401e802b
//
// DO NOT EDIT THIS FILE BY HAND. Regenerate via scripts/gen_ops.py.
// Hand-written instruction bodies live in src/opcodes.cpp and are NOT
// touched by the generator.

#pragma once
#ifndef _H_OPCODES_H_
#define _H_OPCODES_H_

#include <array>
#include <cstdint>
#include <cpu.h>

// DEF_INSTR(opcode, struct_name, mnemonic, cycles_not_taken, cycles_taken)
//
// For unconditional opcodes cycles_not_taken == cycles_taken. For
// conditional branches (JR cc / JP cc / CALL cc / RET cc) the two values
// differ; the instruction body is expected to bump cpu.extra_cycles when
// the branch is taken (see src/opcodes.cpp).
//
// The cycle counts are passed to the instruction base ctor; the user is
// responsible for keeping inc/cpu.h's `instruction` constructor signature
// in sync: instruction(std::string mnemonic, std::uint8_t cycles,
//                      std::uint8_t cycles_taken).
#define DEF_INSTR( o, x, y, c, ct ) \\
\tstruct x: instruction { \\
\t\tx() : instruction(y, c, ct) { \\
\t\t\tif constexpr (((o) & 0xFF00) == 0xCB00) \\
\t\t\t\tinstruction_set_cb[(o) & 0xFF] = this; \\
\t\t\telse \\
\t\t\t\tinstruction_set[(o) & 0xFF] = this; \\
\t\t} \\
\t\tvoid execute(cpu& cpu) override; \\
\t};

#define INST_INSTR(x) extern gbemu::instruction_types::x x##_;

namespace gbemu {
\textern std::array<instruction*, 256> instruction_set;
\textern std::array<instruction*, 256> instruction_set_cb;

\tnamespace instruction_types {
"""

HEADER_MID = """\t}

\tnamespace instructions {
"""

HEADER_EPILOGUE = """\t}
}

#endif /* _H_OPCODES_H_ */
"""


def emit_header(ops: list[dict], out) -> None:
    out.write(HEADER_PREAMBLE)

    for op in ops:
        mnemonic = op['mnemonic']
        cn = make_cn(mnemonic)
        opcode = format_opcode(op['opCode'])
        cycles_nt, cycles_t = parse_cycles(op['cycles'])
        out.write(
            f'\t\tDEF_INSTR({opcode}, {cn}, "{mnemonic}", {cycles_nt}, {cycles_t});\n'
        )

    out.write(HEADER_MID)

    for op in ops:
        cn = make_cn(op['mnemonic'])
        out.write(f'\t\tINST_INSTR({cn});\n')

    out.write(HEADER_EPILOGUE)


def main() -> None:
    here = Path(__file__).parent

    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--db', default=str(here / 'ops_db.json'),
                   help="Path to ops_db.json (default: alongside this script)")
    p.add_argument('--out', default='opcodes.hpp',
                   help="Output path for opcodes.hpp. Use '-' for stdout. "
                        "Default: ./opcodes.hpp (current dir)")
    args = p.parse_args()

    with open(args.db, 'rt', encoding='utf-8') as fp:
        ops = json.load(fp)

    if args.out == '-':
        emit_header(ops, sys.stdout)
    else:
        with open(args.out, 'wt', encoding='utf-8', newline='\n') as fp:
            emit_header(ops, fp)
        print(f"wrote {args.out} ({len(ops)} opcodes)", file=sys.stderr)


if __name__ == '__main__':
    main()
